[package]
name = "study-notes"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["J. Adly <youssefadly237@gmail.com>"]
license = "MIT-0"
description = "a template for making nicely formatted notes"
homepage = ""
repository = "https://github.com/youssefadly237/study-notes"
keywords = ["notes", "academic", "template", "mcq", "study"]
categories = ["layout"]
disciplines = ["education"]
compiler = "0.12.0"
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"